name = "lifegram-api"
account_id = "ff451ba8c41317c7164015927f78b781"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "mini.susagar.sbs/api/*", zone_name = "susagar.sbs" },
  { pattern = "mini.susagar.sbs/miniapp/*", zone_name = "susagar.sbs" },
  { pattern = "mini.susagar.sbs/miniapp", zone_name = "susagar.sbs" },
]

[[d1_databases]]
binding = "DB"
database_name = "lifegram"
database_id = "c980ccc5-97e0-4685-9af5-f61a746f14e1"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "waspros"

[triggers]
crons = ["*/2 * * * *"]

[vars]
NODE_ENV = "production"
APP_DOMAIN = "mini.susagar.sbs"
MINIAPP_URL = "https://lifegram-miniapp.pages.dev/miniapp/"
PAGES_ORIGIN = "https://lifegram-miniapp.pages.dev"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
