/**
 * Telegram MTProto user client (GramJS).
 * Used to enumerate group participants — something the Bot API cannot do.
 *
 * Required env vars:
 *   TELEGRAM_API_ID       — numeric App ID from https://my.telegram.org
 *   TELEGRAM_API_HASH     — App hash from https://my.telegram.org
 *   TELEGRAM_SESSION      — StringSession generated by gen-session script
 */

import { TelegramClient } from "telegram";
import { StringSession } from "telegram/sessions/index.js";
import type { Api } from "telegram";

let _client: TelegramClient | null = null;

function isConfigured(): boolean {
  return !!(
    process.env.TELEGRAM_API_ID &&
    process.env.TELEGRAM_API_HASH &&
    process.env.TELEGRAM_SESSION
  );
}

async function getClient(): Promise<TelegramClient> {
  if (_client?.connected) return _client;

  const apiId   = parseInt(process.env.TELEGRAM_API_ID!,  10);
  const apiHash = process.env.TELEGRAM_API_HASH!;
  const session = new StringSession(process.env.TELEGRAM_SESSION ?? "");

  const client = new TelegramClient(session, apiId, apiHash, {
    connectionRetries: 3,
    useWSS: false,
  });

  await client.connect();
  _client = client;
  return client;
}

export interface Participant {
  id: string;
  username?: string;
  firstName?: string;
}

/**
 * Returns all non-bot participants of a chat using the user MTProto session.
 * Falls back to an empty array (with a logged warning) if not configured.
 */
export async function getGroupParticipants(chatId: string | number): Promise<Participant[]> {
  if (!isConfigured()) {
    console.warn("[user-client] TELEGRAM_SESSION not configured — skipping participant fetch");
    return [];
  }

  try {
    const client = await getClient();

    const participants = await client.getParticipants(chatId, { limit: 0 }) as Api.User[];

    return participants
      .filter(p => !p.bot)
      .map(p => ({
        id: String(p.id),
        username: p.username ?? undefined,
        firstName: p.firstName ?? undefined,
      }));
  } catch (err) {
    console.error("[user-client] getGroupParticipants error:", err);
    return [];
  }
}

/** Returns true when the MTProto session is configured. */
export function hasUserSession(): boolean {
  return isConfigured();
}
