export interface Env {
  DB: D1Database;
  BUCKET: R2Bucket;
  BOT_TOKEN: string;
  ADMIN_ID: string;
  OXAPAY_MERCHANT_KEY: string;
  R2_PUBLIC_URL: string;
  TELEGRAM_API_ID: string;
  TELEGRAM_API_HASH: string;
  MTPROTO_BACKEND_URL: string;
  MTPROTO_API_KEY: string;
  APP_DOMAIN: string;
  MINIAPP_URL: string;
  PAGES_ORIGIN: string;
  AI_INTEGRATIONS_OPENAI_BASE_URL: string;
  AI_INTEGRATIONS_OPENAI_API_KEY: string;
  AI_INTEGRATIONS_ANTHROPIC_BASE_URL: string;
  AI_INTEGRATIONS_ANTHROPIC_API_KEY: string;
  AI_INTEGRATIONS_GEMINI_BASE_URL: string;
  AI_INTEGRATIONS_GEMINI_API_KEY: string;
}
